on: [push, pull_request]
jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd refinery_core && cargo test --lib --all-features -- --test-threads 1
